# version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: erp-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      # MSSQL_SA_PASSWORD: "YourStrong@Password123"
      SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - erp-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -Q 'SELECT 1' -C -b -t 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
      
  erpservice:
    build:
      context: ./ErpService
      dockerfile: Dockerfile
    container_name: erp-service-app
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ErpServiceDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true;Encrypt=True;"
      
     # JWT Settings
      JwtSettings__SecretKey: ${JWT_SECRET_KEY}
      JwtSettings__Issuer: "ErpService"
      JwtSettings__Audience: "ErpServiceClients"
      JwtSettings__ExpirationMinutes: "10"
      
      # User Authentication 
      AuthUsers__admin: ${ADMIN_PASSWORD}
      AuthUsers__erpuser: ${ERPUSER_PASSWORD}
      AuthUsers__riyadh_user: ${RIYADH_USER_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - erp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 45s

volumes:
  sqlserver-data:
    driver: local
    
networks:
  erp-network:
    driver: bridge